blank_issues_enabled: false
contact_links:
  - name: Question or idea
    url: ../../discussions
    about: For anything that is not a bug report.
  - name: Security issue
    url: ../../security/advisories/new
    about: Please report security issues privately.
